apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.23.0
directories:
  - path: config
    contents:
      - path: example-carvel-app
        githubRelease:
          slug: DennisDenuto/example-carvel-app
          tag: v0.0.2
          assetNames: [ "config.*" ]
          disableAutoChecksumValidation: true
      - path: example-carvel-complex-app
        githubRelease:
          slug: DennisDenuto/example-carvel-complex-app
          tag: v0.0.1
          assetNames: [ "config.*" ]
          disableAutoChecksumValidation: true
